// SPDX-License-Identifier: GPL-3.0-or-later
package dev.lyo.callrec.storage

import android.content.Context
import android.net.Uri
import androidx.documentfile.provider.DocumentFile
import dev.lyo.callrec.core.L
import java.io.File
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * Names and creates on-disk targets for raw PCM dumps. Returns a
 * [RecordingFile] which the encoder layer turns into a properly-formatted
 * WAV or AAC/m4a file.
 *
 * Naming convention:
 *   <yyyy-MM-dd_HH-mm-ss>__<callId>__<tag>.<ext>
 *
 * `callId` is a short ULID-ish stamp generated by the caller — it groups the
 * uplink/downlink halves of one call together in the library list.
 */
class RecordingStorage(
    private val appCtx: Context,
    private val folderUriProvider: () -> String? = { null },
) {
    private val baseDir: File by lazy {
        // External files dir is per-app, mounted on shared storage. Indexed
        // by MediaStore (so users can find recordings in any file picker)
        // but wiped on uninstall. Used whenever no SAF folder is configured,
        // or as a fallback if the configured folder becomes inaccessible.
        appCtx.getExternalFilesDir(null)?.resolve("recordings")?.apply { mkdirs() }
            ?: appCtx.filesDir.resolve("recordings").apply { mkdirs() }
    }

    fun newCallId(): String {
        // 5-char base32 of the millisecond timestamp — short, sortable, and
        // unique within the same call (two parallel files share it).
        val v = System.currentTimeMillis()
        val sb = StringBuilder(8)
        var r = v
        repeat(5) { sb.append(BASE32[(r and 0x1F).toInt()]); r = r ushr 5 }
        return sb.reverse().toString()
    }

    fun create(callId: String, tag: String, ext: String): RecordingFile {
        val ts = TIMESTAMP.format(Date())
        val name = "${ts}__${callId}__${tag}"
        val fileName = "$name.$ext"

        val folderUri = folderUriProvider()
        val docUri = folderUri?.let { uri -> createSafDocument(uri, fileName, ext) }
        val path = docUri?.toString() ?: File(baseDir, fileName).absolutePath
        return RecordingFile(name = name, tag = tag, path = path, appCtx = appCtx)
    }

    /** Delegates to [RecordingPaths.delete] — kept here so callers that
     *  already hold a [RecordingStorage] (e.g. [dev.lyo.callrec.recorder.RecorderController])
     *  don't need a separate [Context] reference. */
    fun delete(path: String): Boolean = RecordingPaths.delete(appCtx, path)

    fun listAll(): List<File> =
        baseDir.listFiles()?.sortedByDescending { it.lastModified() } ?: emptyList()

    /**
     * Creates a new document under the user-picked SAF tree. Returns null
     * (falling back to the legacy directory in [create]) if the tree URI is
     * no longer accessible — e.g. permission revoked, SD card removed — so a
     * recording is never silently lost.
     */
    private fun createSafDocument(treeUriString: String, fileName: String, ext: String): Uri? =
        runCatching {
            val tree = DocumentFile.fromTreeUri(appCtx, Uri.parse(treeUriString))
            tree?.takeIf { it.isDirectory && it.canWrite() }
                ?.createFile(mimeFor(ext), fileName)
                ?.uri
        }.onFailure { L.w(TAG, "SAF folder inaccessible, falling back to legacy dir", it) }.getOrNull()

    private fun mimeFor(ext: String): String = when (ext.lowercase(Locale.US)) {
        "wav" -> "audio/wav"
        "m4a" -> "audio/mp4"
        else -> "application/octet-stream"
    }

    companion object {
        // Canonical Crockford base32: 32 unique chars, digits before letters,
        // I/L/O/U omitted. The earlier "ABCDEFGHJKMNPQRSTVWXYZ23456789X"
        // had only 30 unique chars + a duplicate 'X' to pad to 31 — and was
        // indexed with `0x1F` (0..31), so the mask could fall off the end.
        private const val BASE32 = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"
        private val TIMESTAMP = SimpleDateFormat("yyyy-MM-dd_HH-mm-ss", Locale.US)
        private const val TAG = "RecordingStorage"
    }
}
